# Generated by Django 3.0.1 on 2020-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0002_auto_20200102_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(null=True, upload_to='project_avatars'),
        ),
    ]
